### GET /
GET http://localhost:5005

### POST /auth/register
POST http://localhost:5005/auth/register
Content-Type: application/json

{
    "username": "user@gmail.com",
    "password": "testPassword"
}

### POST /auth/login
POST http://localhost:5005/auth/login
Content-Type: application/json

{
    "username": "user@gmail.com",
    "password": "testPassword"
}

###

###

###

###

###

###

###